//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContainerManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shp()
        {
            this.bkgs = new HashSet<bkg>();
        }
    
        public int shipmentId { get; set; }
        public string shipModel { get; set; }
        public string shipmentCode { get; set; }
        public Nullable<int> shipContainer { get; set; }
        public string shipmentStatus { get; set; }
        public System.DateTime shipmentStartDate { get; set; }
        public Nullable<System.DateTime> shipmentEndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bkg> bkgs { get; set; }
    }
}
