//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContainerManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agn()
        {
            this.bkgs = new HashSet<bkg>();
        }
    
        public int agentId { get; set; }
        public string agentName { get; set; }
        public Nullable<int> agentAge { get; set; }
        public Nullable<System.DateTime> agentDOB { get; set; }
        public string agentPhone { get; set; }
        public string agentEmail { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual usr usr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bkg> bkgs { get; set; }
    }
}
