//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContainerManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bkg
    {
        public int bookingId { get; set; }
        public Nullable<int> custId { get; set; }
        public Nullable<int> shipId { get; set; }
        public Nullable<int> agnId { get; set; }
    
        public virtual agn agn { get; set; }
        public virtual cu cu { get; set; }
        public virtual shp shp { get; set; }
    }
}
